INSERT INTO burgers (burger_name) VALUES ('Sub-Conscious Burger (on a sub roll)');
INSERT INTO burgers (burger_name) VALUES ('Sweet Home Avocado Burger');
INSERT INTO burgers (burger_name) VALUES ('I Mint to Do That Burger (comes with mint relish)');
INSERT INTO burgers (burger_name) VALUES ('Take Me Out to the Burger (comes with peanuts & Cracker Jacks)');
INSERT INTO burgers (burger_name) VALUES ('Grandpa Muenster Burger');
INSERT INTO burgers (burger_name) VALUES ('Three Beets to the Wind Burger');
INSERT INTO burgers (burger_name) VALUES ('Itsy Bitsy Teeny Weenie Yellow Polka-Dot Zucchini Burger');
INSERT INTO burgers (burger_name) VALUES ('Gourdon-Hamsey Burger (comes with squash & ham)');
INSERT INTO burgers (burger_name) VALUES ('The Silentil Night Burger (comes with lentils)');
INSERT INTO burgers (burger_name) VALUES ('Poblano Picasso Burger');
INSERT INTO burgers (burger_name) VALUES ("Eggers Can't Be Cheesers (with fried egg & cheese)");
INSERT INTO burgers (burger_name) VALUES ('Fifth Day of Christmas Burger (comes with five golden rings of onion)');
INSERT INTO burgers (burger_name) VALUES ('Paranormal Pepper Jack-tivity Burger (comes with pepper Jack cheese)');
INSERT INTO burgers (burger_name) VALUES ("Don't You Four Cheddar 'Bout Me Burger (comes with four kinds of cheddar)");
INSERT INTO burgers (burger_name) VALUES ("Let's Give 'Em Something Shiitake 'Bout Burger");